apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: ml-brand-gender
spec:
  name: ml-brnd-gender-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: ml-brand-gender
          image: msabr027/ml-brand-gender:0.1
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    annotations:
      predictor_version: "0.1"
      seldon.io/svc-name: ml-brand-gender-svc
    name: ml-brand-gender-graph
    replicas: 1